import { emptyAnalysis } from '../../core/app-state.js';
import { resetPageNavigation } from '../../core/navigation-history.js';

export function resetDocumentState(state, clearOcrLayoutSelection, { opening }) {
  state.zoom = 1;
  state.rotation = 0;
  state.selectedPage = 1;
  state.searchQuery = '';
  state.searchResults = [];
  state.pageOrder = [];
  state.ocrResult = null;
  state.ocrUserDictionary = '';
  state.ocrSuspectReviewStates = [];
  state.ocrZones = [];
  state.selectedOcrZoneId = null;
  clearOcrLayoutSelection();
  state.domainResult = null;
  state.domainError = null;
  state.domainBusy = false;
  state.domainRevision = 0;
  state.aecLastCalibrationId = null;
  state.aecLastMeasurementId = null;
  state.viewerMode = 'native';
  state.snapshotRegion = { x: 0.1, y: 0.1, width: 0.8, height: 0.8 };
  state.snapshotDpi = '192';
  state.showGrid = false;
  state.presentationMode = false;
  const navigation = resetPageNavigation();
  state.navigationHistory = [...navigation.history];
  state.navigationIndex = navigation.index;
  state.comparisonReport = null;
  state.comparisonFileName = null;
  state.redactionFullPage = false;
  state.redactionPlans = [];
  state.selectedRedactionPlanId = '';
  state.selectedRedactionMarkId = '';
  state.fullPageRedactionResult = null;
  state.prepressResult = null;
  state.standardsValidationResult = null;
  state.accessibilityReviewResult = null;
  state.accessibilityAltTextCandidateLocator = '';
  state.accessibilityAltText = '';
  state.accessibilityAltTextProposalResult = null;
  state.accessibilityDocumentLanguage = '';
  state.accessibilityDocumentTitle = '';
  state.incrementalAccessibilityMetadataResult = null;
  state.pdfkitInspectionResult = null;
  state.pdfkitLayerGroups = [];
  state.pdfkitLayerVisibility = [];
  state.pdfkitLayerInspectionDigest = null;
  state.pdfkitLayerStatus = 'idle';
  state.pdfkitLayerError = null;
  state.pdfkitLayerResult = null;
  state.annotationFlattenResult = null;
  state.attachmentRemovalResult = null;
  state.incrementalBleedBoxResult = null;
  state.incrementalGoToLinkResult = null;
  state.incrementalNamedDestinationResult = null;
  state.incrementalMetadataResult = null;
  state.incrementalPageVectorResult = null;
  state.pageTextResult = null;
  state.javascriptRemovalResult = null;
  state.pdfkitMutationResult = null;
  state.pdfkitProtectionResult = null;
  state.pdfkitProtectionRemovalResult = null;
  state.pdfkitSanitizationResult = null;
  state.pdfkitTextFieldWidgetResult = null;
  state.pdfkitMetadata = { title: '', author: '', subject: '', keywords: '' };
  state.pdfkitPageBox = 'crop';
  state.pdfkitPageBoxRect = { x: 0, y: 0, width: 612, height: 792 };
  state.pdfkitPageRotation = '90';
  state.pdfkitAnnotationSubtype = 'freeText';
  state.pdfkitAnnotationContents = 'Review note';
  state.pdfkitAnnotationRect = { x: 36, y: 36, width: 180, height: 80 };
  state.pdfkitWidgetIndex = '';
  state.pdfkitFormValue = '';
  state.pdfkitButtonState = 'on';
  state.pdfkitLinkTargetPage = '1';
  state.incrementalNamedDestinationName = 'destination-1';
  state.incrementalNamedDestinationTargetPage = '1';
  state.pdfkitLocalLinkRemovalIndex = '';
  state.pdfkitLinkRect = { x: 36, y: 36, width: 180, height: 40 };
  state.incrementalPageVectorRect = { x: 36, y: 36, width: 120, height: 120 };
  state.pageTextRun = { x: 36, y: 36, size: 12, text: '' };
  state.pdfkitOutlineLabel = 'New bookmark';
  state.pdfkitOutlineTargetPage = '1';
  state.pdfkitOutlineRemovalIndex = '';
  state.pdfkitOutlineRenameIndex = '';
  state.pdfkitOutlineRenameLabel = 'Renamed bookmark';
  state.pdfkitLineContents = 'Review line';
  state.pdfkitLineStart = { x: 72, y: 72 };
  state.pdfkitLineEnd = { x: 252, y: 152 };
  state.pdfkitInkContents = 'Review ink path';
  state.pdfkitInkPoints = '72,72;162,112;252,152';
  state.pdfkitExistingAnnotationIndex = '';
  state.pdfkitExistingAnnotationContents = 'Updated review note';
  state.pdfkitExistingAnnotationRect = { x: 36, y: 36, width: 180, height: 80 };
  state.acroFormCheckboxFieldName = 'check-1';
  state.acroFormTextFieldName = 'text-1';
  state.acroFormTextFieldPage = '1';
  state.acroFormTextFieldRect = { x: 36, y: 36, width: 180, height: 24 };
  state.acroFormCheckboxPage = '1';
  state.acroFormCheckboxRect = { x: 36, y: 36, width: 18, height: 18 };
  state.acroFormRadioGroupName = 'choice-1';
  state.acroFormRadioOptions = [
    { label: 'Option 1', page: '1', rect: { x: 36, y: 36, width: 18, height: 18 } },
    { label: 'Option 2', page: '1', rect: { x: 36, y: 64, width: 18, height: 18 } },
  ];
  state.acroFormStatus = 'idle';
  state.acroFormError = null;
  state.acroFormResult = null;
  state.aecMeasurementIds = []; state.aecLegendStatus = 'idle'; state.aecLegendError = null; state.aecLegendResult = null;
  state.scannerDiscoveryStatus = 'idle'; state.scannerDiscoveryError = null; state.scannerDiscoveryResult = null; state.scannerDiscoveryEvidence = null; state.scannerDevices = []; state.batesStatus = 'idle'; state.batesError = null; state.batesResult = null;
  state.analysis = emptyAnalysis(opening ? 'loading' : 'idle');
  if (opening) state.analysis.progress = 'Preparing local analysis…';
  state.error = null;
  if (opening) {
    state.view = 'editor';
  } else {
    state.busyAction = null;
    state.canCancel = false;
  }
}
