import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdtemp, writeFile, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import test from 'node:test';
import { PdfJpegImageReplacementInputBroker } from '../scripts/host/pdf-jpeg-image-replacement-input-broker.mjs';

test('replacement broker never deletes an untrusted forged artifact ID', async () => { const root = await mkdtemp(join(tmpdir(), 'jpeg-replacement-broker-')); const inputId = '123e4567-e89b-12d3-a456-426614174000'; const bytes = Buffer.from('jpeg-input!!'); const sha = createHash('sha256').update(bytes).digest('hex'); const path = join(root, 'input.jpg'); await writeFile(path, bytes, { mode: 0o600 }); const deleted = []; const inputs = { getInput: () => ({ mediaType: 'image/jpeg', extension: '.jpg', size: bytes.length, sha256: sha }), getSourcePath: () => path, verifyInput: async () => {} }; const service = { replace: async () => ({ kind: 'pdf-jpeg-image-replacement', artifact: { id: 'forged', sha256: 'f'.repeat(64) } }) };
const store = { getArtifact: () => ({ id: 'real', sha256: 'r'.repeat(64) }), deleteArtifact: async (id) => deleted.push(id) }; const broker = new PdfJpegImageReplacementInputBroker({ inputs, service, store }); await assert.rejects(broker.replace('doc', { profile: 'local-pdf-jpeg-image-replacement-v1', sourceSha256: 'a'.repeat(64), inputId, inputSha256: sha, page: 1, resourceName: 'Im0' }), { code: 'PDF_JPEG_IMAGE_REPLACEMENT_RESULT_INVALID' }); assert.deepEqual(deleted, []); await rm(root, { recursive: true, force: true }); });

async function brokerFixture({ artifact = { id: '223e4567-e89b-12d3-a456-426614174000', sha256: 'f'.repeat(64) }, serviceResult = null, getArtifact = null, deleteArtifact = async () => {} } = {}) {
  const root = await mkdtemp(join(tmpdir(), 'jpeg-replacement-broker-hostile-')); const inputId = '123e4567-e89b-12d3-a456-426614174000'; const bytes = Buffer.from('jpeg-input!!'); const sha = createHash('sha256').update(bytes).digest('hex'); const path = join(root, 'input.jpg'); await writeFile(path, bytes, { mode: 0o600 });
  const fullArtifact = artifact.documentId ? artifact : { id: artifact.id, documentId: '223e4567-e89b-12d3-a456-426614174000', displayName: 'jpeg-image-replacement.pdf', mediaType: 'application/pdf', size: 128, sha256: artifact.sha256, operation: {}, createdAt: '2026-07-21T00:00:00.000Z' }; const inputs = { getInput: () => ({ mediaType: 'image/jpeg', extension: '.jpg', size: bytes.length, sha256: sha }), getSourcePath: () => path, verifyInput: async () => {} }; const service = { replace: async () => serviceResult ?? { kind: 'pdf-jpeg-image-replacement', artifact: fullArtifact } }; const store = { getArtifact: getArtifact ?? (() => fullArtifact), deleteArtifact }; const request = { profile: 'local-pdf-jpeg-image-replacement-v1', sourceSha256: 'a'.repeat(64), inputId, inputSha256: sha, page: 1, resourceName: 'Im0' }; return { root, inputs, service, store, request, artifact: fullArtifact };
}

test('replacement broker rejects accessor-backed request objects before reading input records', async () => {
  let reads = 0; const fixture = await brokerFixture(); fixture.inputs.getInput = () => { reads += 1; throw new Error('input must not be read'); }; const request = {}; Object.defineProperties(request, { profile: { enumerable: true, value: 'local-pdf-jpeg-image-replacement-v1' }, sourceSha256: { enumerable: true, value: 'a'.repeat(64) }, inputId: { enumerable: true, value: fixture.request.inputId }, inputSha256: { enumerable: true, value: fixture.request.inputSha256 }, page: { enumerable: true, value: 1 }, resourceName: { enumerable: true, get() { throw new Error('getter'); } } }); const broker = new PdfJpegImageReplacementInputBroker(fixture); await assert.rejects(broker.replace('doc', request), { code: 'INVALID_PDF_JPEG_IMAGE_REPLACEMENT_OPTIONS' }); assert.equal(reads, 0); await rm(fixture.root, { recursive: true, force: true });
  const symbols = await brokerFixture(); const symbolRequest = { ...symbols.request, [Symbol('unexpected')]: true }; const symbolBroker = new PdfJpegImageReplacementInputBroker(symbols); await assert.rejects(symbolBroker.replace('doc', symbolRequest), { code: 'INVALID_PDF_JPEG_IMAGE_REPLACEMENT_OPTIONS' }); await rm(symbols.root, { recursive: true, force: true });
});

test('replacement broker revokes the exact trusted artifact on cancellation and reports typed cleanup failure', async () => {
  const controller = new AbortController(); const deleted = []; const fixture = await brokerFixture({ deleteArtifact: async (id) => deleted.push(id) }); const broker = new PdfJpegImageReplacementInputBroker(fixture); const originalReplace = fixture.service.replace; fixture.service.replace = async (...args) => { const result = await originalReplace(...args); controller.abort(new Error('cancelled')); return result; }; await assert.rejects(broker.replace('doc', fixture.request, { signal: controller.signal }), { code: 'JOB_CANCELLED' }); assert.deepEqual(deleted, [fixture.artifact.id]); await rm(fixture.root, { recursive: true, force: true });
  const cleanup = await brokerFixture({ deleteArtifact: async () => { throw new Error('delete failed'); } }); const cleanupBroker = new PdfJpegImageReplacementInputBroker(cleanup); const cleanupController = new AbortController(); const cleanupReplace = cleanup.service.replace; cleanup.service.replace = async (...args) => { const result = await cleanupReplace(...args); cleanupController.abort(new Error('cancelled')); return result; }; await assert.rejects(cleanupBroker.replace('doc', cleanup.request, { signal: cleanupController.signal }), { code: 'PDF_JPEG_IMAGE_REPLACEMENT_CLEANUP_FAILED' }); await rm(cleanup.root, { recursive: true, force: true });
});

test('replacement broker never deletes an artifact when trusted-store lookup throws', async () => {
  const deleted = []; const fixture = await brokerFixture({ getArtifact: () => { throw new Error('store lookup failed'); }, deleteArtifact: async (id) => deleted.push(id) }); const broker = new PdfJpegImageReplacementInputBroker(fixture); await assert.rejects(broker.replace('doc', fixture.request), /store lookup failed/u); assert.deepEqual(deleted, []); await rm(fixture.root, { recursive: true, force: true });
});

test('replacement broker rejects accessor-backed and proxy result records before store cleanup authority', async () => {
  const accessor = await brokerFixture(); const result = { kind: 'pdf-jpeg-image-replacement', artifact: accessor.artifact }; Object.defineProperty(result, 'secret', { enumerable: true, get() { throw new Error('secret getter'); } }); accessor.service.replace = async () => result; const deleted = []; accessor.store.deleteArtifact = async (id) => deleted.push(id); const broker = new PdfJpegImageReplacementInputBroker(accessor); await assert.rejects(broker.replace('doc', accessor.request), { code: 'PDF_JPEG_IMAGE_REPLACEMENT_RESULT_INVALID' }); assert.deepEqual(deleted, []); await rm(accessor.root, { recursive: true, force: true });
  const proxied = await brokerFixture(); proxied.service.replace = async () => new Proxy({ kind: 'pdf-jpeg-image-replacement', artifact: proxied.artifact }, { ownKeys() { throw new Error('proxy'); } }); const proxyBroker = new PdfJpegImageReplacementInputBroker(proxied); await assert.rejects(proxyBroker.replace('doc', proxied.request), { code: 'PDF_JPEG_IMAGE_REPLACEMENT_RESULT_INVALID' }); await rm(proxied.root, { recursive: true, force: true });
});
