import assert from 'node:assert/strict';
import { EventEmitter } from 'node:events';
import test from 'node:test';
import { handleJpegImageReplacementRoute } from '../scripts/host/routes/jpeg-image-replacement-routes.mjs';

const body = Object.freeze({ profile: 'local-pdf-jpeg-image-replacement-v1', sourceSha256: 'a'.repeat(64), inputId: '123e4567-e89b-12d3-a456-426614174000', inputSha256: 'b'.repeat(64), page: 1, resourceName: 'Im0' });
function context({ value = body, aborted = false } = {}) { const response = new EventEmitter(); const controller = new AbortController(); if (aborted) controller.abort(); const calls = []; const deleted = []; return { request: { method: 'POST' }, response, url: new URL('http://local/api/documents/doc/replace-jpeg'), documentId: 'doc', operation: 'replace-jpeg', processing: { signal: controller.signal }, store: { deleteArtifact: async (id) => deleted.push(id) }, jpegImageReplacementReady: true, jpegImageReplacement: { replace: async (...args) => { calls.push(args); return { kind: 'pdf-jpeg-image-replacement', artifact: { id: 'artifact' } };
} }, bodyLimit: 2048, exactJsonObject: (candidate, keys) => Boolean(candidate) && typeof candidate === 'object' && !Array.isArray(candidate) && Object.keys(candidate).length === keys.length && Object.keys(candidate).every((key) => keys.includes(key)), method: (candidate, expected) => assert.equal(candidate.method, expected), readJson: async () => value, json: (_response, status, result) => { response.status = status; response.value = result; }, calls, deleted }; }
test('replace-jpeg route validates exact request and returns result', async () => { const value = context(); assert.equal(await handleJpegImageReplacementRoute(value), true); assert.equal(value.response.status, 201); assert.deepEqual(value.calls[0][1], body); const bad = context({ value: { ...body, extra: true } }); await assert.rejects(handleJpegImageReplacementRoute(bad), { code: 'INVALID_PDF_JPEG_IMAGE_REPLACEMENT_OPTIONS' }); });
test('replace-jpeg route schedules artifact revocation on disconnect', async () => { const value = context({ aborted: true }); assert.equal(await handleJpegImageReplacementRoute(value), true); assert.deepEqual(value.deleted, ['artifact']); });
