import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import test from 'node:test';
import { normalizePdfBatesNumbering, PDF_BATES_NUMBERING_PROFILE } from '../scripts/host/pdf-bates-numbering-contract.mjs';
import { inspectPdfBatesNumbering, writePdfBatesNumbering } from '../scripts/host/pdf-bates-numbering-writer.mjs';
function source() { const b = ['<< /Type /Catalog /Pages 2 0 R >>', '<< /Type /Pages /Count 1 /Kids [3 0 R] >>', '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /CropBox [0 0 612 792] /Resources << >> /Contents 4 0 R >>', '<< /Length 0 >>\nstream\n\nendstream']; let x = '%PDF-1.7\n'; const o=[]; for(let i=0;i<b.length;i+=1){o.push(Buffer.byteLength(x));x+=`${i+1} 0 obj\n${b[i]}\nendobj\n`;} const sx=Buffer.byteLength(x); x+=`xref\n0 5\n0000000000 65535 f \n${o.map(v=>`${String(v).padStart(10,'0')} 00000 n \n`).join('')}trailer\n<< /Size 5 /Root 1 0 R >>\nstartxref\n${sx}\n%%EOF\n`; return Buffer.from(x,'latin1'); }
function req(s, extra={}) { return { profile: PDF_BATES_NUMBERING_PROFILE, sourceSha256: createHash('sha256').update(s).digest('hex'), pages:[1], start:1, prefix:'', suffix:'', padding:3, position:'bottom-left', margin:12, fontSize:10, ...extra }; }
function encryptedSource() { const original = source().toString('latin1'); const split = original.indexOf('xref\n'); const body = original.slice(0, split); const encryption = '5 0 obj\n<< /Filter /Standard /V 1 /Length 40 /R 2 /O <0000000000000000000000000000000000000000> /U <0000000000000000000000000000000000000000> >>\nendobj\n'; const fullBody = body + encryption; const offsets = []; for (let object = 1; object <= 5; object += 1) offsets.push(fullBody.indexOf(`${object} 0 obj`)); const xrefOffset = Buffer.byteLength(fullBody, 'latin1'); const xref = `xref\n0 6\n0000000000 65535 f \n${offsets.map((offset) => `${String(offset).padStart(10, '0')} 00000 n \n`).join('')}trailer\n<< /Size 6 /Root 1 0 R /Encrypt 5 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`; return Buffer.from(fullBody + xref, 'latin1'); }
test('Bates contract and writer reject malformed requests and preserve source prefix', () => { const s=source(); const p=writePdfBatesNumbering(s,req(s)); assert.equal(p.proof.revisionCount,2); assert.equal(p.proof.resourceName,'BatesHelv'); assert.equal(p.bytes.subarray(0,s.length).equals(s),true); const inspected = inspectPdfBatesNumbering(s,p.bytes,req(s)); assert.equal(inspected.outputSha256,p.proof.outputSha256); assert.deepEqual(inspected.pages,p.proof.pages.map(({ page, text }) => ({ page, text }))); assert.throws(()=>normalizePdfBatesNumbering(req(s,{pages:[1,1]})),{code:'INVALID_PDF_BATES_NUMBERING'}); assert.throws(()=>normalizePdfBatesNumbering(req(s,{position:'middle'})),{code:'INVALID_PDF_BATES_NUMBERING'}); });
test('Bates writer rejects hostile text, geometry, encryption, and font collisions', () => { const s=source(); assert.throws(()=>writePdfBatesNumbering(s,req(s,{prefix:'\uE000'})),{code:'INVALID_PDF_BATES_NUMBERING'}); assert.throws(()=>writePdfBatesNumbering(s,req(s,{margin:1_000_001})),{code:'INVALID_PDF_BATES_NUMBERING'}); const encrypted=encryptedSource(); assert.throws(()=>writePdfBatesNumbering(encrypted,req(encrypted)),{code:'UNSUPPORTED_PDF_BATES_NUMBERING_SOURCE'}); const collision=Buffer.from(s.toString('latin1').replace('/Resources << >>','/Resources << /Font << /BatesHelv 9 0 R >> >>'),'latin1'); assert.throws(()=>writePdfBatesNumbering(collision,req(collision)),{code:'UNSUPPORTED_PDF_BATES_NUMBERING_SOURCE'}); });
test('Bates contract and independent inspection reject descriptor and output tampering', () => { const s=source(); const base=req(s); const getterPages=[]; Object.defineProperty(getterPages,'0',{get(){return 1;},enumerable:true}); Object.defineProperty(getterPages,'length',{value:1}); assert.throws(()=>normalizePdfBatesNumbering({...base,pages:getterPages}),{code:'INVALID_PDF_BATES_NUMBERING'}); const symbolPages=[1]; symbolPages[Symbol('extra')]=true; assert.throws(()=>normalizePdfBatesNumbering({...base,pages:symbolPages}),{code:'INVALID_PDF_BATES_NUMBERING'}); const built=writePdfBatesNumbering(s,base); const tampered=Buffer.from(built.bytes); const marker=Buffer.from('303031','latin1'); const at=tampered.lastIndexOf(marker); assert.ok(at > s.length); tampered[at + 5] = '2'.charCodeAt(0); assert.throws(()=>inspectPdfBatesNumbering(s,tampered,base),{code:'INVALID_PDF_BATES_NUMBERING_OUTPUT'}); });
test('Bates writer rejects indirect font and nested resource aliases', () => { const s=source(); const indirectFont=Buffer.from(s.toString('latin1').replace('/Resources << >>','/Resources << /Font 9 0 R >>'),'latin1'); assert.throws(()=>writePdfBatesNumbering(indirectFont,req(indirectFont)),{code:'UNSUPPORTED_PDF_BATES_NUMBERING_SOURCE'}); const indirectResource=Buffer.from(s.toString('latin1').replace('/Resources << >>','/Resources << /XObject << /Im0 9 0 R >> >>'),'latin1'); assert.throws(()=>writePdfBatesNumbering(indirectResource,req(indirectResource)),{code:'UNSUPPORTED_PDF_BATES_NUMBERING_SOURCE'}); });
