import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { access, mkdtemp, readFile, writeFile } from 'node:fs/promises';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import test from 'node:test';
import { deflateSync } from 'node:zlib';
import { PDF_JPEG_IMAGE_REPLACEMENT_PROFILE, inspectPdfJpegImageReplacement, writePdfJpegImageReplacement } from '../scripts/host/pdf-jpeg-image-replacement-writer.mjs';
import { parsePdfStructure, resolvePdfObject } from '../scripts/host/pdf-classic-structure.mjs';
import { planClassicObjectTransaction } from '../scripts/host/pdf-classic-object-transaction.mjs';
import { parseClassicPdfStructure, resolveClassicPdfObject } from '../scripts/host/pdf-classic-structure.mjs';

const execFileAsync = promisify(execFile);
const JPEG = Buffer.from('/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD/wAARCAABAAEDAREAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAACP/EABQQAQAAAAAAAAAAAAAAAAAAAAD/xAAVAQEBAAAAAAAAAAAAAAAAAAAHCf/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/ADoDFU3/2Q==', 'base64');
function fixture() { const content = 'q 80 0 0 60 10 20 cm /Im0 Do Q\n'; const bodies = ['<< /Type /Catalog /Pages 2 0 R >>', '<< /Type /Pages /Count 1 /Kids [3 0 R] >>', '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 100 100] /CropBox [0 0 100 100] /Resources << /XObject << /Im0 5 0 R >> >> /Contents 4 0 R >>', `<< /Length ${content.length} >>\nstream\n${content}endstream`, `<< /Type /XObject /Subtype /Image /Width 1 /Height 1 /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${JPEG.length} >>\nstream\n${JPEG.toString('latin1')}\nendstream`]; const chunks = ['%PDF-1.4\n']; const offsets = []; bodies.forEach((body, index) => { offsets[index + 1] = Buffer.byteLength(chunks.join(''), 'latin1'); chunks.push(`${index + 1} 0 obj\n${body}\nendobj\n`); }); const xref = Buffer.byteLength(chunks.join(''), 'latin1');
chunks.push(`xref\n0 6\n0000000000 65535 f \n${offsets.slice(1).map((offset) => `${String(offset).padStart(10, '0')} 00000 n \n`).join('')}trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`); return Buffer.from(chunks.join(''), 'latin1'); }
function request(source, jpegBytes = JPEG) { return { profile: PDF_JPEG_IMAGE_REPLACEMENT_PROFILE, sourceSha256: createHash('sha256').update(source).digest('hex'), page: 1, resourceName: 'Im0', jpegBytes }; }
function customFixture(content) { const bodies = ['<< /Type /Catalog /Pages 2 0 R >>', '<< /Type /Pages /Count 1 /Kids [3 0 R] >>', '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 100 100] /CropBox [0 0 100 100] /Resources << /XObject << /Im0 5 0 R >> >> /Contents 4 0 R >>', `<< /Length ${content.length} >>\nstream\n${content}endstream`, `<< /Type /XObject /Subtype /Image /Width 1 /Height 1 /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${JPEG.length} >>\nstream\n${JPEG.toString('latin1')}\nendstream`]; const chunks = ['%PDF-1.4\n']; const offsets = []; bodies.forEach((body, index) => { offsets[index + 1] = Buffer.byteLength(chunks.join(''), 'latin1'); chunks.push(`${index + 1} 0 obj\n${body}\nendobj\n`); }); const xref = Buffer.byteLength(chunks.join(''), 'latin1');
chunks.push(`xref\n0 6\n0000000000 65535 f \n${offsets.slice(1).map((offset) => `${String(offset).padStart(10, '0')} 00000 n \n`).join('')}trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`); return Buffer.from(chunks.join(''), 'latin1'); }
function compressedStructuralFixture(content = 'q 80 0 0 60 10 20 cm /Im0 Do Q\n') { const catalog = '<< /Type /Catalog /Pages 4 0 R >>'; const resources = '<< /XObject << /Im0 8 0 R >> >>'; const directory = `1 0 9 ${Buffer.byteLength(catalog, 'latin1') + 1} `; const payload = deflateSync(Buffer.from(`${directory}${catalog} ${resources}`, 'latin1')); const objectStream = `3 0 obj\n<< /Type /ObjStm /N 2 /First ${directory.length} /Filter /FlateDecode /Length ${payload.length} >>\nstream\n`; const pages = '4 0 obj\n<< /Type /Pages /Count 1 /Kids [5 0 R] >>\nendobj\n'; const page = `5 0 obj\n<< /Type /Page /Parent 4 0 R /MediaBox [0 0 100 100] /CropBox [0 0 100 100] /Resources 9 0 R /Contents 6 0 R >>\nendobj\n`; const contents = `6 0 obj\n<< /Length ${content.length} >>\nstream\n${content}endstream\nendobj\n`;
const image = `8 0 obj\n<< /Type /XObject /Subtype /Image /Width 1 /Height 1 /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${JPEG.length} >>\nstream\n${JPEG.toString('latin1')}\nendstream\nendobj\n`; const header = Buffer.from(`%PDF-1.7\n${objectStream}`, 'latin1'); const objectStreamBody = Buffer.concat([header, payload, Buffer.from('\nendstream\nendobj\n', 'latin1')]); const chunks = [objectStreamBody, Buffer.from(pages + page + contents + image, 'latin1')]; const offsets = new Map([[3, 0]]); let at = objectStreamBody.length; offsets.set(4, at); at += Buffer.byteLength(pages, 'latin1'); offsets.set(5, at); at += Buffer.byteLength(page, 'latin1'); offsets.set(6, at); at += Buffer.byteLength(contents, 'latin1'); offsets.set(8, at); const xrefOffset = at + Buffer.byteLength(image, 'latin1');
const rows = Buffer.alloc(10 * 7); const row = (number, type, field2, field3) => { const p = number * 7; rows[p] = type; rows.writeUInt32BE(field2, p + 1); rows.writeUInt16BE(field3, p + 5); }; row(0, 0, 0, 65535); row(1, 2, 3, 0); row(2, 0, 0, 0); row(3, 1, 9, 0); row(4, 1, offsets.get(4), 0); row(5, 1, offsets.get(5), 0); row(6, 1, offsets.get(6), 0); row(7, 1, xrefOffset, 0); row(8, 1, offsets.get(8), 0); row(9, 2, 3, 1); const xref = Buffer.from(`7 0 obj\n<< /Type /XRef /W [1 4 2] /Index [0 10] /Size 10 /Root 1 0 R /Length ${rows.length} >>\nstream\n`, 'latin1'); return Buffer.concat([...chunks, xref, rows, Buffer.from(`\nendstream\nendobj\nstartxref\n${xrefOffset}\n%%EOF\n`, 'latin1')]); }

test('JPEG XObject replacement preserves identity and only changes the target stream', async (context) => {
  const source = fixture(); const replacement = Buffer.from(JPEG); replacement[replacement.length - 3] ^= 1; const result = writePdfJpegImageReplacement(source, request(source, replacement)); assert.equal(result.bytes.subarray(0, source.length).equals(source), true); assert.equal(result.proof.targetReference, '5 0 R'); assert.deepEqual(inspectPdfJpegImageReplacement(source, result.bytes, request(source, replacement)), result.proof); assert.equal(result.proof.invocation.ctm.join(' '), '80 0 0 60 10 20');
  try { await Promise.all(['/opt/homebrew/bin/pdfinfo', '/opt/homebrew/bin/pdfimages', '/opt/homebrew/bin/pdftocairo'].map((path) => access(path))); } catch { context.skip('Poppler is unavailable.'); return; }
  const root = await mkdtemp(join(tmpdir(), 'pdf-jpeg-replacement-')); const sourcePath = join(root, 'source.pdf'); const outputPath = join(root, 'output.pdf'); await writeFile(sourcePath, source); await writeFile(outputPath, result.bytes); const before = (await execFileAsync('/opt/homebrew/bin/pdfimages', ['-list', sourcePath])).stdout; const after = (await execFileAsync('/opt/homebrew/bin/pdfimages', ['-list', outputPath])).stdout; assert.match(before, /jpeg/u); assert.match(after, /jpeg/u); await execFileAsync('/opt/homebrew/bin/pdftocairo', ['-png', '-singlefile', outputPath, join(root, 'render')]); assert.ok((await readFile(join(root, 'render.png'))).length > 100);
});

test('JPEG XObject replacement rejects aliases, non-image resources, ambiguous Do use, and mismatched components', () => {
  const source = fixture(); assert.throws(() => writePdfJpegImageReplacement(source, request(source, Buffer.from([0xff, 0xd8, 0xff, 0xd9]))), { code: 'INVALID_PDF_JPEG_IMAGE_REPLACEMENT' }); const alias = Buffer.from(source.toString('latin1').replace('/Im0 5 0 R >>', '/Im0 5 0 R /Alias 5 0 R >>'), 'latin1'); assert.throws(() => writePdfJpegImageReplacement(alias, request(alias)), { code: 'UNSUPPORTED_PDF_JPEG_IMAGE_REPLACEMENT' }); const dynamic = Buffer.from(source.toString('latin1').replace('/Im0 Do', '/Im0 Do /Im0 Do'), 'latin1'); assert.throws(() => writePdfJpegImageReplacement(dynamic, request(dynamic)), { code: 'UNSUPPORTED_PDF_JPEG_IMAGE_REPLACEMENT' });
});
test('JPEG XObject replacement restores CTM after nested graphics state', () => { const source = customFixture('q 80 0 0 60 10 20 cm q 2 0 0 2 1 1 cm /Im0 Do Q Q\n'); const result = writePdfJpegImageReplacement(source, request(source)); assert.deepEqual(result.proof.invocation.ctm, [160, 0, 0, 120, 90, 80]); });
test('JPEG XObject replacement preserves an admitted prior incremental revision', () => { const base = fixture(); const structure = parseClassicPdfStructure(base); const content = resolveClassicPdfObject(structure, { type: 'ref', object: 4, generation: 0 }); const prior = planClassicObjectTransaction({ sourceBytes: base, sourceStructure: structure, updates: [{ reference: { type: 'ref', object: 4, generation: 0 }, value: content.value, streamBytes: base.subarray(content.streamStart, content.streamStart + content.streamLength) }], additions: [], info: { kind: 'preserve' }, changingId: null }); const source = Buffer.concat([base, prior.revision.bytes]); const result = writePdfJpegImageReplacement(source, request(source)); assert.equal(result.proof.revisionCount, 3); assert.equal(result.bytes.subarray(0, source.length).equals(source), true); });
test('JPEG XObject replacement admits compressed structural dictionaries with an ordinary target image stream', () => { const source = compressedStructuralFixture(); const result = writePdfJpegImageReplacement(source, request(source)); assert.equal(result.proof.targetReference, '8 0 R'); assert.equal(result.bytes.subarray(0, source.length).equals(source), true); });
