import assert from 'node:assert/strict';
import { chmod, mkdtemp, readdir, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { randomUUID } from 'node:crypto';
import { join } from 'node:path';
import test from 'node:test';
import { DocumentStore } from '../scripts/host/document-store.mjs';
import { PdfTextReflowService } from '../scripts/host/pdf-text-reflow-service.mjs';
import { makeTextReflowPdf, textReflowRequest } from './host-pdf-text-reflow-fixtures.mjs';

async function setup(t) { const root = await mkdtemp(join(tmpdir(), 'pdf-text-reflow-')); const store = await new DocumentStore({ root }).initialize(); t.after(() => store.dispose()); const bytes = makeTextReflowPdf(); const source = await store.createDocument({ stream: (async function* () { yield bytes; }()), displayName: 'source.pdf' }); return { root, store, bytes, source, request: textReflowRequest(bytes), service: new PdfTextReflowService({ store }) }; }
function wrapped(base, overrides = {}) { const store = {}; for (const name of ['getDocument', 'getSourcePath', 'verifySource', 'createJobWorkspace', 'cleanupJob', 'promotePdfArtifact', 'getArtifact', 'deleteArtifact']) store[name] = (overrides[name] ?? base[name]).bind(base); return store; }

test('text-reflow service promotes an independently inspected artifact and cleans its workspace', async (t) => { const state = await setup(t); const result = await state.service.reflow(state.source.id, state.request); assert.equal(result.kind, 'pdf-text-reflow'); assert.equal(result.artifact.mediaType, 'application/pdf'); assert.equal(result.proof.fixedSlotReflow, true); assert.deepEqual(await readdir(join(state.root, 'jobs')), []); await state.store.deleteArtifact(result.artifact.id); });
test('text-reflow service rejects forged promotion without authorizing deletion', async (t) => { const state = await setup(t); const deleted = []; const forged = { id: randomUUID(), documentId: state.source.id, displayName: 'text-reflow.pdf', mediaType: 'application/pdf', size: 1, sha256: '0'.repeat(64), operation: {} }; const store = wrapped(state.store, { promotePdfArtifact: async () => forged, deleteArtifact: async (id) => { deleted.push(id); } }); await assert.rejects(new PdfTextReflowService({ store }).reflow(state.source.id, state.request), { code: 'PDF_TEXT_REFLOW_OUTPUT_INVALID' }); assert.deepEqual(deleted, []); });
test('text-reflow service revokes a valid promotion when artifact reread throws', async (t) => { const state = await setup(t); let artifact; const store = wrapped(state.store, { promotePdfArtifact: async (...args) => { artifact = await state.store.promotePdfArtifact(...args); return artifact; }, getArtifact: async () => { throw new Error('reread failed'); } }); await assert.rejects(new PdfTextReflowService({ store }).reflow(state.source.id, state.request), { code: 'PDF_TEXT_REFLOW_OUTPUT_INVALID' }); assert.throws(() => state.store.getArtifact(artifact.id), { code: 'ARTIFACT_NOT_FOUND' }); });
test('text-reflow service revokes a valid promotion when artifact reread mismatches', async (t) => { const state = await setup(t); let artifact; const store = wrapped(state.store, { promotePdfArtifact: async (...args) => { artifact = await state.store.promotePdfArtifact(...args); return artifact; }, getArtifact: async (id) => ({ ...state.store.getArtifact(id), sha256: '0'.repeat(64) }) }); await assert.rejects(new PdfTextReflowService({ store }).reflow(state.source.id, state.request), { code: 'PDF_TEXT_REFLOW_OUTPUT_INVALID' }); assert.throws(() => state.store.getArtifact(artifact.id), { code: 'ARTIFACT_NOT_FOUND' }); });
test('text-reflow service revokes after post-promotion cancellation', async (t) => { const state = await setup(t); const controller = new AbortController(); let artifact; const store = wrapped(state.store, { promotePdfArtifact: async (...args) => { artifact = await state.store.promotePdfArtifact(...args); controller.abort(); return artifact; } }); await assert.rejects(new PdfTextReflowService({ store }).reflow(state.source.id, state.request, { signal: controller.signal }), { code: 'JOB_CANCELLED' }); assert.throws(() => state.store.getArtifact(artifact.id), { code: 'ARTIFACT_NOT_FOUND' }); });
test('text-reflow service revokes after post-promotion source drift', async (t) => { const state = await setup(t); let verifies = 0; const store = wrapped(state.store, { verifySource: async (...args) => { verifies += 1; if (verifies === 3) { const path = state.store.getSourcePath(state.source.id); await chmod(path, 0o600); await writeFile(path, Buffer.concat([state.bytes, Buffer.from('drift')])); } return state.store.verifySource(...args); } }); await assert.rejects(new PdfTextReflowService({ store }).reflow(state.source.id, state.request), { code: 'SOURCE_INTEGRITY_FAILED' }); assert.deepEqual(await readdir(join(state.root, 'jobs')), []); });
test('text-reflow service aggregates workspace and artifact cleanup failures', async (t) => { const state = await setup(t); const controller = new AbortController(); const store = wrapped(state.store, { promotePdfArtifact: async (...args) => { const artifact = await state.store.promotePdfArtifact(...args); controller.abort(); return artifact; }, cleanupJob: async () => { throw new Error('workspace cleanup failed'); }, deleteArtifact: async () => { throw new Error('artifact revoke failed'); } }); await assert.rejects(new PdfTextReflowService({ store }).reflow(state.source.id, state.request, { signal: controller.signal }), { code: 'PDF_TEXT_REFLOW_CLEANUP_FAILED' }); });
