import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdtemp, readFile, readdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import test from 'node:test';
import { DocumentStore } from '../scripts/host/document-store.mjs';
import { PdfAcroFormTabOrderTooltipService } from '../scripts/host/pdf-acroform-tab-order-tooltip-service.mjs';
import { makeButtonWidgetPdf } from './host-pdfkit-test-fixtures-b.js';

const PROFILE = 'local-pdf-acroform-tab-order-tooltip-v1';
function digest(bytes) { return createHash('sha256').update(bytes).digest('hex'); }
function request(bytes, tooltip = 'Accessible name') {
  const sourceSha256 = digest(bytes); const fingerprint = digest(Buffer.from(['pdfkit-inspector:opaque-locator:v1', `source-sha256=${sourceSha256}`, 'page=1', 'annotation-index=0', 'subtype=widget', 'widget-type=button'].join('\n')));
  return { profile: PROFILE, sourceSha256, target: { page: 1, annotationIndex: 0, fingerprint }, tooltip };
}
async function setup(t) { const root = await mkdtemp('/private/tmp/pdf-acroform-tab-order-tooltip-service-'); const store = await new DocumentStore({ root }).initialize(); t.after(() => store.dispose()); const bytes = makeButtonWidgetPdf(); const source = await store.createDocument({ stream: (async function* () { yield bytes; }()), displayName: 'source.pdf' }); return { root, store, bytes, source, request: request(bytes), service: new PdfAcroFormTabOrderTooltipService({ store }) }; }

test('tab-order and tooltip service promotes a verified separate artifact and cleans its workspace', async (t) => { const state = await setup(t); const result = await state.service.add(state.source.id, state.request); assert.equal(result.artifact.documentId, state.source.id); assert.equal(result.proof.tabOrder, 'S'); assert.equal(result.proof.sourcePrefixPreserved, true); assert.notEqual(result.artifact.sha256, state.source.sha256); assert.deepEqual(await readdir(join(state.root, 'jobs')), []); assert.deepEqual(await readFile(state.store.getSourcePath(state.source.id)), state.bytes); });

test('tab-order and tooltip service rejects stale source, hostile descriptors, cancellation, and promotion tamper', async (t) => {
  const state = await setup(t); await assert.rejects(state.service.add(state.source.id, { ...state.request, sourceSha256: '0'.repeat(64) }), { code: 'SOURCE_VERSION_MISMATCH' });
  const getter = { ...state.request }; Object.defineProperty(getter, 'tooltip', { enumerable: true, get() { throw new Error('getter'); } }); await assert.rejects(state.service.add(state.source.id, getter), { code: 'INVALID_ACROFORM_TAB_ORDER_TOOLTIP_OPTIONS' });
  const controller = new AbortController(); controller.abort(); await assert.rejects(state.service.add(state.source.id, state.request, { signal: controller.signal }), { code: 'JOB_CANCELLED' });
  const base = state.store; const wrapped = {}; for (const name of ['getDocument', 'getSourcePath', 'verifySource', 'createJobWorkspace', 'cleanupJob', 'deleteArtifact']) wrapped[name] = base[name].bind(base); wrapped.promotePdfArtifact = async (documentId, outputPath, options) => { const bytes = await readFile(outputPath); await writeFile(outputPath, Buffer.concat([bytes, Buffer.from('tamper')])); return base.promotePdfArtifact(documentId, outputPath, options); }; const service = new PdfAcroFormTabOrderTooltipService({ store: wrapped }); await assert.rejects(service.add(state.source.id, state.request), { code: 'ARTIFACT_DIGEST_MISMATCH' }); assert.deepEqual(await readdir(join(state.root, 'jobs')), []);
  const drift = await setup(t); let verifies = 0; const driftStore = {}; for (const name of ['getDocument', 'getSourcePath', 'createJobWorkspace', 'cleanupJob', 'promotePdfArtifact', 'deleteArtifact']) driftStore[name] = drift.store[name].bind(drift.store); driftStore.verifySource = async (...args) => { verifies += 1; if (verifies === 2) await writeFile(drift.store.getSourcePath(drift.source.id), Buffer.concat([drift.bytes, Buffer.from('drift')])); return drift.store.verifySource(...args); }; await assert.rejects(new PdfAcroFormTabOrderTooltipService({ store: driftStore }).add(drift.source.id, drift.request), { code: 'SOURCE_INTEGRITY_FAILED' });
});

test('tab-order and tooltip service revokes a promoted artifact when cancellation arrives after promotion', async (t) => { const state = await setup(t); const controller = new AbortController(); const base = state.store; const wrapped = {}; for (const name of ['getDocument', 'getSourcePath', 'verifySource', 'createJobWorkspace', 'cleanupJob', 'deleteArtifact']) wrapped[name] = base[name].bind(base); wrapped.promotePdfArtifact = async (...args) => { const artifact = await base.promotePdfArtifact(...args); controller.abort(); return artifact; }; const service = new PdfAcroFormTabOrderTooltipService({ store: wrapped }); await assert.rejects(service.add(state.source.id, state.request, { signal: controller.signal }), { code: 'JOB_CANCELLED' }); assert.deepEqual(await readdir(join(state.root, 'jobs')), []); });

test('tab-order and tooltip service reports combined workspace and artifact cleanup failure', async (t) => { const state = await setup(t); const base = state.store; const wrapped = {}; for (const name of ['getDocument', 'getSourcePath', 'verifySource', 'createJobWorkspace', 'promotePdfArtifact', 'deleteArtifact']) wrapped[name] = base[name].bind(base); wrapped.cleanupJob = async () => { throw new Error('workspace cleanup failed'); }; let revoked = null; wrapped.deleteArtifact = async (id) => { revoked = id; throw new Error('artifact revoke failed'); }; const service = new PdfAcroFormTabOrderTooltipService({ store: wrapped }); await assert.rejects(service.add(state.source.id, state.request), (error) => { assert.equal(error.code, 'ACROFORM_TAB_ORDER_TOOLTIP_CLEANUP_FAILED'); assert.equal(error.cause instanceof AggregateError, true); return true; }); assert.match(revoked ?? '', /^[0-9a-f-]{8,}$/u); });

test('tab-order and tooltip service does not revoke an unrelated forged promotion identity', async (t) => { const state = await setup(t); const base = state.store; const wrapped = {}; for (const name of ['getDocument', 'getSourcePath', 'verifySource', 'createJobWorkspace', 'cleanupJob']) wrapped[name] = base[name].bind(base); let deleted = null; wrapped.deleteArtifact = async (id) => { deleted = id; }; wrapped.promotePdfArtifact = async () => ({ id: 'unrelated-artifact', documentId: state.source.id, sha256: '0'.repeat(64), size: 1 }); const service = new PdfAcroFormTabOrderTooltipService({ store: wrapped }); await assert.rejects(service.add(state.source.id, state.request), { code: 'ACROFORM_TAB_ORDER_TOOLTIP_OUTPUT_INVALID' }); assert.equal(deleted, null); });
