import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test from 'node:test';
import { makeMultiPagePdf } from './pdf-fixture.js';
import { PDF_SPECIALIST_CONTENT_PROFILE, inspectPdfSpecialistContent } from '../scripts/host/pdf-specialist-content-inventory.mjs';
import { PdfSpecialistContentService } from '../scripts/host/pdf-specialist-content-service.mjs';
const documentId = '11111111-1111-4111-8111-111111111111';
async function setup(context, options = {}) { const root = await mkdtemp(join(tmpdir(), 'specialist-service-')); context.after(() => rm(root, { recursive: true, force: true })); const bytes = makeMultiPagePdf(['one']); const sha256 = createHash('sha256').update(bytes).digest('hex'); const path = join(root, 'source.pdf'); await writeFile(path, bytes, { mode: 0o600 }); let calls = 0; const store = { getDocument: () => ({ id: documentId, size: bytes.length, sha256 }), getSourcePath: () => path, verifySource: async () => { calls += 1; if (options.mutate && calls === 2) await writeFile(path, Buffer.from('changed')); } }; return { service: new PdfSpecialistContentService({ store, core: options.core ?? { inspectPdfSpecialistContent } }), request: { profile: PDF_SPECIALIST_CONTENT_PROFILE, sourceSha256: sha256 }, sha256, path }; }
test('specialist service verifies source before and after extraction', async (context) => { const setupResult = await setup(context); const result = await setupResult.service.inspect(documentId, setupResult.request, { sourceSha256: setupResult.sha256 }); assert.equal(result.evidence.sourceDigestReverified, true); });
test('specialist service maps cancellation, stale source, and source mutation', async (context) => { const setupResult = await setup(context); const controller = new AbortController(); controller.abort(); await assert.rejects(setupResult.service.inspect(documentId, setupResult.request, { sourceSha256: setupResult.sha256, signal: controller.signal }), { code: 'JOB_CANCELLED', status: 499 }); await assert.rejects(setupResult.service.inspect(documentId, setupResult.request, { sourceSha256: '0'.repeat(64) }), { code: 'SOURCE_VERSION_MISMATCH', status: 409 }); const mutated = await setup(context, { mutate: true }); await assert.rejects(mutated.service.inspect(documentId, mutated.request, { sourceSha256: mutated.sha256 }), { code: 'SOURCE_INTEGRITY_FAILED', status: 500 }); });
test('specialist service snapshots immutable inventory output', async (context) => { const setupResult = await setup(context, { core: { inspectPdfSpecialistContent: (...args) => inspectPdfSpecialistContent(...args) } }); const result = await setupResult.service.inspect(documentId, setupResult.request, { sourceSha256: setupResult.sha256 }); assert.equal(Object.isFrozen(result), true); assert.equal(Object.isFrozen(result.evidence), true); assert.throws(() => { result.pageCount = 99; }, TypeError); });
