import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { mkdtemp, readdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test from 'node:test';
import { DocumentStore } from '../scripts/host/document-store.mjs';
import { PdfAcroFormBarcodeService } from '../scripts/host/pdf-acroform-barcode-service.mjs';
import { barcodeFieldRequest, makeBarcodeFieldPdf } from './host-pdf-acroform-barcode-fixtures.mjs';

async function setup(t) { const root = await mkdtemp(join(tmpdir(), 'pdf-acroform-barcode-')); const store = await new DocumentStore({ root }).initialize(); t.after(() => store.dispose()); const bytes = makeBarcodeFieldPdf(); const source = await store.createDocument({ stream: (async function* () { yield bytes; }()), displayName: 'source.pdf' }); return { root, store, bytes, source, request: barcodeFieldRequest(bytes), service: new PdfAcroFormBarcodeService({ store }) }; }
function wrapped(base, overrides = {}) { const store = {}; for (const method of ['getDocument', 'getSourcePath', 'verifySource', 'createJobWorkspace', 'cleanupJob', 'promotePdfArtifact', 'getArtifact', 'deleteArtifact']) store[method] = (overrides[method] ?? base[method]).bind(base); return store; }

test('barcode service promotes a retained independently inspected artifact and cleans workspace', async (t) => { const state = await setup(t); const result = await state.service.add(state.source.id, state.request); assert.equal(result.kind, 'pdf-acroform-barcode'); assert.equal(result.artifact.displayName, 'barcode-field.pdf'); assert.equal(result.proof.readOnly, true); assert.equal(result.artifact.operation.expected.addedObjectCount, 3); assert.equal(result.artifact.operation.expected.changedObjectCount, 5); assert.deepEqual(await readdir(join(state.root, 'jobs')), []); await state.store.deleteArtifact(result.artifact.id); });
test('barcode service rejects forged promotion without authorizing deletion', async (t) => { const state = await setup(t); const deleted = []; const forged = { id: randomUUID(), documentId: state.source.id, displayName: 'barcode-field.pdf', mediaType: 'application/pdf', size: 1, sha256: '0'.repeat(64), operation: {} }; const store = wrapped(state.store, { promotePdfArtifact: async () => forged, deleteArtifact: async (id) => { deleted.push(id); } }); await assert.rejects(new PdfAcroFormBarcodeService({ store }).add(state.source.id, state.request), { code: 'PDF_ACROFORM_BARCODE_OUTPUT_INVALID' }); assert.deepEqual(deleted, []); });
test('barcode service revokes a valid promotion when retained artifact reread fails', async (t) => { const state = await setup(t); let artifact; const store = wrapped(state.store, { promotePdfArtifact: async (...args) => { artifact = await state.store.promotePdfArtifact(...args); return artifact; }, getArtifact: async () => { throw new Error('reread failed'); } }); await assert.rejects(new PdfAcroFormBarcodeService({ store }).add(state.source.id, state.request), { code: 'PDF_ACROFORM_BARCODE_OUTPUT_INVALID' }); assert.throws(() => state.store.getArtifact(artifact.id), { code: 'ARTIFACT_NOT_FOUND' }); });
test('barcode service revokes after post-promotion cancellation', async (t) => { const state = await setup(t); const controller = new AbortController(); let artifact; const store = wrapped(state.store, { promotePdfArtifact: async (...args) => { artifact = await state.store.promotePdfArtifact(...args); controller.abort(); return artifact; } }); await assert.rejects(new PdfAcroFormBarcodeService({ store }).add(state.source.id, state.request, { signal: controller.signal }), { code: 'JOB_CANCELLED' }); assert.throws(() => state.store.getArtifact(artifact.id), { code: 'ARTIFACT_NOT_FOUND' }); });
test('barcode service validates exact request and store surface', async (t) => { const state = await setup(t); const extra = { ...state.request, extra: true }; await assert.rejects(state.service.add(state.source.id, extra), { code: 'PDF_ACROFORM_BARCODE_OPTIONS_INVALID' }); assert.throws(() => new PdfAcroFormBarcodeService({ store: {} }), TypeError); });
