import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import test from 'node:test';
import { inspectPdfAcroFormRadio, preparePdfAcroFormRadio, PDF_ACROFORM_RADIO_PROFILE } from '../scripts/host/pdf-acroform-radio-writer.mjs';

function source() { let c=['%PDF-1.7\n']; const o=[]; const b=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Count 1 /Kids [3 0 R] >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /CropBox [0 0 612 792] /Resources << >> /Contents 4 0 R >>','<< /Length 0 >>\nstream\n\nendstream']; for(let i=0;i<b.length;i+=1){o.push(Buffer.byteLength(c.join(''),'latin1'));c.push(`${i+1} 0 obj\n${b[i]}\nendobj\n`);}const x=Buffer.byteLength(c.join(''),'latin1');c.push(`xref\n0 5\n0000000000 65535 f \n${o.map(v=>`${String(v).padStart(10,'0')} 00000 n \n`).join('')}trailer\n<< /Size 5 /Root 1 0 R >>\nstartxref\n${x}\n%%EOF\n`);return Buffer.from(c.join(''),'latin1'); }
function d(b){return createHash('sha256').update(b).digest('hex');}
function req(s, extra={}){return { profile:PDF_ACROFORM_RADIO_PROFILE, sourceSha256:d(s), groupName:'Choice', options:[{label:'First',page:1,rect:{x:10,y:700,width:20,height:20}},{label:'Second',page:1,rect:{x:40,y:700,width:20,height:20}}], ...extra };}
test('radio writer emits one parent with exact unchecked kids and deterministic states',()=>{const s=source();const r=preparePdfAcroFormRadio(s,req(s));assert.equal(r.proof.options.length,2);assert.equal(r.proof.options[0].stateName,'Opt1');assert.equal(r.proof.options[1].stateName,'Opt2');assert.equal(r.proof.sourcePrefixPreserved,true);assert.deepEqual(inspectPdfAcroFormRadio(s,r.bytes,req(s)),r.proof);});
test('radio writer rejects duplicate labels, malformed geometry, digest drift, and tampering',()=>{const s=source();assert.throws(()=>preparePdfAcroFormRadio(s,req(s,{options:[{label:'Same',page:1,rect:{x:1,y:1,width:2,height:2}},{label:'Same',page:1,rect:{x:5,y:1,width:2,height:2}}]})),{code:'INVALID_PDF_ACROFORM_RADIO'});assert.throws(()=>preparePdfAcroFormRadio(s,req(s,{sourceSha256:'0'.repeat(64)})),{code:'INVALID_PDF_ACROFORM_RADIO'});const r=preparePdfAcroFormRadio(s,req(s));const t=Buffer.from(r.bytes);t[t.length-10]^=1;assert.throws(()=>inspectPdfAcroFormRadio(s,t,req(s)),{code:'INVALID_PDF_ACROFORM_RADIO_OUTPUT'});});
test('radio writer rejects an encrypted trailer before writing',()=>{const encrypted=Buffer.from(source().toString('latin1').replace('/Root 1 0 R', '/Root 1 0 R /Encrypt 9 0 R'),'latin1');assert.throws(()=>preparePdfAcroFormRadio(encrypted,req(encrypted)),{code:'UNSUPPORTED_PDF_ACROFORM_RADIO_SOURCE'});});
