import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdtemp, readdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import test from 'node:test';
import { DocumentStore } from '../scripts/host/document-store.mjs';
import { PdfBatesNumberingService } from '../scripts/host/pdf-bates-numbering-service.mjs';
function source(){const b=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Count 1 /Kids [3 0 R] >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /CropBox [0 0 612 792] /Resources << >> /Contents 4 0 R >>','<< /Length 0 >>\nstream\n\nendstream'];let x='%PDF-1.7\n';const o=[];for(let i=0;i<b.length;i++){o.push(Buffer.byteLength(x));x+=`${i+1} 0 obj\n${b[i]}\nendobj\n`;}const q=Buffer.byteLength(x);x+=`xref\n0 5\n0000000000 65535 f \n${o.map(v=>`${String(v).padStart(10,'0')} 00000 n \n`).join('')}trailer\n<< /Size 5 /Root 1 0 R >>\nstartxref\n${q}\n%%EOF\n`;return Buffer.from(x,'latin1');}
function req(s,e={}){return {profile:'local-pdf-bates-numbering-v1',sourceSha256:createHash('sha256').update(s).digest('hex'),pages:[1],start:1,prefix:'',suffix:'',padding:3,position:'bottom-left',margin:12,fontSize:10,...e};}
async function setup(t){const root=await mkdtemp('/private/tmp/pdf-bates-service-');const store=await new DocumentStore({root}).initialize();t.after(()=>store.dispose());const bytes=source();const document=await store.createDocument({stream:(async function*(){yield bytes;})(),displayName:'source.pdf'});return {store,bytes,document,service:new PdfBatesNumberingService({store})};}
test('Bates service promotes derived output and preserves source',async t=>{const s=await setup(t);const result=await s.service.add(s.document.id,req(s.bytes));assert.equal(result.proof.pageCount,1);assert.deepEqual(await readFile(s.store.getSourcePath(s.document.id)),s.bytes);assert.deepEqual(await readdir(join(s.store.root,'jobs')),[]);});
test('Bates service binds current digest and rejects cancellation',async t=>{const s=await setup(t);await assert.rejects(s.service.add(s.document.id,req(s.bytes,{sourceSha256:'0'.repeat(64)})),{code:'SOURCE_VERSION_MISMATCH'});const controller=new AbortController();controller.abort();await assert.rejects(s.service.add(s.document.id,req(s.bytes),{signal:controller.signal}),{code:'JOB_CANCELLED'});});
test('Bates service rechecks cancellation before promotion',async t=>{const s=await setup(t);const controller=new AbortController();let verifies=0;const verify=s.store.verifySource.bind(s.store);s.store.verifySource=async(...args)=>{verifies+=1;const result=await verify(...args);if(verifies===2) controller.abort();return result;};await assert.rejects(s.service.add(s.document.id,req(s.bytes),{signal:controller.signal}),{code:'JOB_CANCELLED'});assert.deepEqual(await readdir(join(s.store.root,'jobs')),[]);});
test('Bates service rejects output tampering during promotion',async t=>{const s=await setup(t);const promote=s.store.promotePdfArtifact.bind(s.store);s.store.promotePdfArtifact=async(documentId,path,options)=>{const bytes=await readFile(path);bytes[bytes.length-1]=bytes[bytes.length-1]===10?9:10;await writeFile(path,bytes);return promote(documentId,path,options);};await assert.rejects(s.service.add(s.document.id,req(s.bytes)),{code:'ARTIFACT_DIGEST_MISMATCH'});assert.deepEqual(await readdir(join(s.store.root,'jobs')),[]);});
test('Bates service revokes an artifact when cancellation arrives after promotion',async t=>{const s=await setup(t);const controller=new AbortController();const promote=s.store.promotePdfArtifact.bind(s.store);s.store.promotePdfArtifact=async(...args)=>{const artifact=await promote(...args);controller.abort();return artifact;};await assert.rejects(s.service.add(s.document.id,req(s.bytes),{signal:controller.signal}),{code:'JOB_CANCELLED'});assert.deepEqual(await readdir(join(s.store.root,'artifacts')),[]);});
test('Bates service rejects source drift before promotion',async t=>{const s=await setup(t);let verifies=0;const verify=s.store.verifySource.bind(s.store);s.store.verifySource=async(...args)=>{verifies+=1;if(verifies===2){const changed=Buffer.from(s.bytes);changed[changed.length-1]=changed[changed.length-1]===10?9:10;await writeFile(s.store.getSourcePath(s.document.id),changed);}return verify(...args);};await assert.rejects(s.service.add(s.document.id,req(s.bytes)),{code:'SOURCE_INTEGRITY_FAILED'});assert.deepEqual(await readdir(join(s.store.root,'jobs')),[]);});
test('Bates service surfaces cleanup and promotion identity failures',async t=>{const s=await setup(t);s.store.cleanupJob=async()=>{throw new Error('cleanup failed');};await assert.rejects(s.service.add(s.document.id,req(s.bytes)),{code:'BATES_CLEANUP_FAILED'});const s2=await setup(t);s2.store.promotePdfArtifact=async()=>({id:'missing',documentId:s2.document.id,size:1,sha256:'0'.repeat(64)});await assert.rejects(s2.service.add(s2.document.id,req(s2.bytes)),{code:'BATES_CLEANUP_FAILED'});});
