// Bootstrap is intentionally separate from authenticated API families: the
// router applies the local-host check before this handler is reached.
export async function handleBootstrapRoute(context) {
  const {
    pathname, request, response, service, inputs, conversion, domainFacade, prepress,
    aecArtifacts, projectBundles, accessibilityRemediations, standardsValidations, reviewSidecar,
    incrementalMetadata, incrementalBleedBox, incrementalGoToLink, incrementalNamedDestination,
    incrementalPageVector, pageText, textReflow, fileAudioAttachments, reviewMeasurements, reviewAnnotationImportExport, reviewSharedExchange, commentsToOffice, reviewNotifications, formJavaScriptInventory, fullPageRedaction, printerMarks, layerDefaults, incrementalAccessibilityMetadata, javascriptRemoval, attachmentRemoval,
    annotationFlatten, fastWebView, acroFormCheckbox, acroFormRadio, acroFormTextField, acroFormChoice, batesNumbering, aecMeasurementLegend,
    pdfkitInspections, pdfkitOutlineSplits, pdfkitMutations, pdfkitProtection,
    pdfkitSanitization, pdfkitTextFieldWidget, redactionPlans, redactionPlanReports, signatureTrustReady, signingIdentityReady, hiddenDataSanitization, jpegImage, pageLabels, advancedSearch, specialistContent, scannerDiscovery, scannerDiscoveryReady, scannerAcquisition, scannerAcquisitionReady, pluginSandboxProbeReady, token,
    acroFormFillSave, acroFormValidation,
    method, requireLocalFetchMetadata, json, sanitizedEngineAvailability,
  } = context;
  if (pathname !== '/api/bootstrap') return false;

  method(request, 'GET');
  requireLocalFetchMetadata(request);
  const engines = sanitizedEngineAvailability(await service.availability());
  const fastWebViewProbe = await fastWebView?.probe?.();
  json(response, 200, {
    sessionToken: token,
    host: {
      localOnly: true,
      sourceImmutable: true,
      conversionReady: Boolean(inputs && conversion),
      prepressReady: Boolean(prepress),
      outputIntentProfileReady: prepress?.outputIntentProfileReady === true,
      workflowDomainsReady: Boolean(domainFacade),
      aecArtifactsReady: Boolean(aecArtifacts),
      aecNativeReady: Boolean(aecArtifacts?.nativeAvailable),
      projectBundlesReady: Boolean(projectBundles),
      portableProjectBundlesReady: Boolean(projectBundles),
      accessibilityRemediationReady: Boolean(accessibilityRemediations),
      standardsValidationReady: Boolean(standardsValidations),
      incrementalMetadataReady: Boolean(incrementalMetadata),
      incrementalBleedBoxReady: Boolean(incrementalBleedBox),
      incrementalGoToLinkReady: Boolean(incrementalGoToLink),
      incrementalNamedDestinationReady: Boolean(incrementalNamedDestination),
      incrementalPageVectorReady: Boolean(incrementalPageVector),
      pageTextReady: Boolean(pageText),
      textReflowReady: typeof textReflow?.reflow === 'function',
      fileAudioAttachmentsReady: typeof fileAudioAttachments?.add === 'function',
      reviewMeasurementsReady: typeof reviewMeasurements?.create === 'function',
      reviewAnnotationImportExportReady: typeof reviewAnnotationImportExport?.importExport === 'function',
      reviewSharedExchangeReady: typeof reviewSharedExchange?.export === 'function' && typeof reviewSharedExchange?.import === 'function',
      commentsToOfficeReady: typeof commentsToOffice?.export === 'function',
      reviewNotificationsReady: typeof reviewNotifications?.generate === 'function' && typeof reviewNotifications?.markRead === 'function',
      reviewSidecarReady: typeof reviewSidecar?.setStatus === 'function' && typeof reviewSidecar?.inspect === 'function',
      formJavaScriptInventoryReady: typeof formJavaScriptInventory?.inspect === 'function',
      fullPageRedactionReady: Boolean(fullPageRedaction),
      fullPageRedactionBatchReady: typeof fullPageRedaction?.updateBatch === 'function',
      printerMarksReady: typeof printerMarks?.create === 'function',
      layerDefaultsReady: Boolean(layerDefaults),
      incrementalAccessibilityMetadataReady: Boolean(incrementalAccessibilityMetadata),
      javascriptRemovalReady: Boolean(javascriptRemoval),
      attachmentRemovalReady: Boolean(attachmentRemoval),
      annotationFlattenReady: Boolean(annotationFlatten),
      fastWebViewReady: fastWebViewProbe?.available === true,
      pdfkitInspectionReady: Boolean(pdfkitInspections),
      pdfkitOutlineSplitReady: Boolean(pdfkitOutlineSplits),
      pdfkitMutationReady: Boolean(pdfkitMutations),
      pdfkitProtectionReady: Boolean(pdfkitProtection),
      pdfkitSanitizationReady: Boolean(pdfkitSanitization),
      pdfkitTextFieldWidgetReady: Boolean(pdfkitTextFieldWidget),
      redactionPlansReady: Boolean(redactionPlans),
      redactionPlanReportsReady: Boolean(redactionPlanReports),
      signatureTrustReady: signatureTrustReady === true,
      signingIdentityReady: signingIdentityReady === true,
      hiddenDataSanitizationReady: Boolean(hiddenDataSanitization),
      acroFormCheckboxReady: Boolean(acroFormCheckbox),
      acroFormRadioReady: Boolean(acroFormRadio),
      acroFormTextFieldReady: Boolean(acroFormTextField),
      acroFormChoiceReady: Boolean(acroFormChoice),
      acroFormFillSaveReady: typeof acroFormFillSave?.fill === 'function',
      acroFormValidationReady: typeof acroFormValidation?.validate === 'function',
      batesNumberingReady: Boolean(batesNumbering),
      aecMeasurementLegendReady: Boolean(aecMeasurementLegend),
      jpegImageReady: Boolean(jpegImage),
      pageLabelsReady: Boolean(pageLabels),
      advancedSearchReady: Boolean(advancedSearch),
      specialistContentReady: typeof specialistContent?.inspect === 'function',
      scannerDiscoveryReady: scannerDiscoveryReady === true && Boolean(scannerDiscovery),
      scannerAcquisitionReady: scannerAcquisitionReady === true && Boolean(scannerAcquisition),
      pluginSandboxProbeReady: pluginSandboxProbeReady === true,
    },
    engines,
  });
  return true;
}
