import { pdfKitAppState } from './pdfkit-app-state.js';
import { acroFormAppState } from './acroform-app-state.js';

export function emptyAnalysis(status = 'idle') {
  return {
    status,
    documentId: null,
    progress: null,
    inspection: null,
    structure: null,
    textPages: [],
    thumbnails: [],
    thumbnailNotice: null,
    fonts: [],
    images: [],
    attachments: [],
    signatures: null,
    sha256: null,
  };
}

function redactionState() {
  return {
    redactionText: '',
    redactionFullPage: false,
    redactionRegion: { x: 0.1, y: 0.1, width: 0.4, height: 0.08 },
    redactionPlans: [],
    selectedRedactionPlanId: '',
    selectedRedactionMarkId: '',
    fullPageRedactionResult: null,
  };
}

export function createAppState({ documentSnapshot, snapshotClipboardReady = false } = {}) {
  if (typeof snapshotClipboardReady !== 'boolean') {
    throw new TypeError('snapshotClipboardReady must be a boolean.');
  }
  return {
    view: 'editor',
    document: documentSnapshot,
    documentTabs: { tabs: [], activeTabId: null, maxTabs: 8 },
    registry: null,
    prototypeCoverage: null,
    prototypeSummary: null,
    summary: { families: 0, capabilities: 0, implemented: 0, planned: 0 },
    zoom: 1,
    rotation: 0,
    dragging: false,
    error: null,
    pluginQuery: '',
    familyFilter: 'all',
    selectedPlugin: 'skeleton:ocr',
    probeResult: null,
    pluginSandboxStatus: null,
    host: { status: 'connecting', engines: [] },
    analysis: emptyAnalysis(),
    selectedPage: 1,
    searchQuery: '',
    searchResults: [],
    busyAction: null,
    canCancel: false,
    pageOrder: [],
    ocrLanguages: [],
    ocrLanguage: 'eng',
    ocrCleanupPreset: 'document',
    ocrSegmentation: 'auto',
    ocrUserDictionary: '',
    ocrDetectTables: true,
    ocrZones: [],
    selectedOcrZoneId: null,
    selectedOcrRecordIndex: null,
    selectedOcrTableCandidate: null,
    ocrResult: null,
    ocrSuspectReviewStates: [],
    ocrLayoutResult: null,
    ocrBatchFiles: [],
    ocrBatchResult: null,
    ocrBatchTemporaryDocumentIds: [],
    creationTitle: 'Untitled',
    creationText: '',
    blankPageCount: '1',
    splitRulePages: '10',
    copySourcePage: '1',
    domainOperations: null,
    selectedDomainOperation: { group: 'review', operation: 'createAnnotation' },
    domainPayload: '{\n  "input": {\n    "type": "comment",\n    "page": 1,\n    "rectangle": [36, 36, 180, 80],\n    "text": "Review note",\n    "author": "Local reviewer"\n  },\n  "options": { "expectedRevision": 0 }\n}',
    domainResult: null,
    domainError: null,
    domainBusy: false,
    domainRevision: 0,
    aecCalibrationPoints: '36,36;108,36',
    aecRealLength: '1',
    aecCalibrationUnit: 'ft',
    aecMeasurementPoints: '36,36;108,36',
    aecMeasurementKind: 'distance',
    aecDisplayUnit: 'ft',
    aecMeasurementLabel: 'Measured element',
    aecLastCalibrationId: null,
    aecLastMeasurementId: null,
    aecMeasurementIds: [],
    aecLegendStatus: 'idle',
    aecLegendError: null,
    aecLegendResult: null,
    scannerDiscoveryStatus: 'idle',
    scannerDiscoveryError: null,
    scannerDiscoveryResult: null,
    scannerDiscoveryEvidence: null,
    scannerDevices: [],
    batesPages: '1', batesStart: '0', batesPrefix: '', batesSuffix: '', batesPadding: '6', batesPosition: 'bottom-left', batesMargin: '12', batesFontSize: '10', batesStatus: 'idle', batesError: null, batesResult: null,
    viewerMode: 'native',
    controlledRaster: { status: 'idle', page: null, dpi: 192, url: null, error: null },
    loupeRaster: { status: 'idle', page: null, dpi: 192, url: null, error: null },
    snapshotRegion: { x: 0.1, y: 0.1, width: 0.8, height: 0.8 },
    snapshotDpi: '192',
    snapshotClipboardReady,
    showGrid: false,
    presentationMode: false,
    navigationHistory: [1],
    navigationIndex: 0,
    searchCaseSensitive: false,
    searchWholeWord: false,
    textExportFormat: 'text',
    cropRegion: { x: 0.05, y: 0.05, width: 0.9, height: 0.9 },
    resizeWidth: '612',
    resizeHeight: '792',
    overlayPlacement: 'watermark',
    overlayText: 'CONFIDENTIAL',
    ...redactionState(),
    comparisonMode: 'content',
    comparisonReport: null,
    comparisonFileName: null,
    prepressDpi: '144',
    preflightProfile: 'print-review',
    impositionMarks: false,
    prepressResult: null,
    standardsProfile: 'pdfa-2u',
    standardsValidationResult: null,
    accessibilityReviewResult: null,
    accessibilityAltTextCandidateLocator: '',
    accessibilityAltText: '',
    accessibilityAltTextProposalResult: null,
    accessibilityDocumentLanguage: '',
    accessibilityDocumentTitle: '',
    incrementalAccessibilityMetadataResult: null,
    ...pdfKitAppState(),
    ...acroFormAppState(),
  };
}
